### ISSUE TITLE
Nightly regression test doesn't test the emulator

### ISSUE THREAD

**Issue by Emoun** [t-crest/patmos-misc#13]
The nightly regression test only uses the simulator during its test. This means the hardware implementation is currently not being tested as far as I can tell.

The benchmark repository does have support for testing using the emulator. To do that the initial cmake command must include the `-DENABLE_EMULATOR=true` argument, which adds emulator-run versions of many tests. When this argument is not provided all tests run on the simulator only. This is currently how the nightly regression tests run.

We should update the nightly regression setup to also test using the emulator, to ensure the hardware acts as expected. However, we shouldn't change the setup such that the emulator must be used at all times, as we can then no longer test LLVM on Travis-CI, which should only be tested using the simulator.

**Comment by schoeberl** [comment]
Can you do this?

Martin

**Comment by Emoun** [comment]
I can give it a try

**Comment by Emoun** [comment]
I have tried to make the nightly test run on the emulator, but it doesn't seem to work.

I first updated the benchmark repository to use the correct emulator name (previously it was apparently `patmos-emulator` but now its `patemu`). Doing this on my own machine was enough to make the `misc/build.sh -t bench` begin testing the emulator too.
I also tried specifically addint the `ENABLE_EMULATOR=true` flag to the `misc/build.sh`, but this made no difference.

I don't really know why it doesn't work. It might be if the emulator is not building correctly, in which case the benchmark repository automatically disables emulator testing.
Could someone check Helena to see what is going on?

**Comment by Thonner** [comment]
The new emulator for chisel 3 was pulled into master 3 hours before you're comment. The new emulator requires Verilator to be installed on the machine to be build. This could be the case. 
Also some features are still missing in the new emulator which might be needed for some of these tests:
- Printing of register content every cycle
- Read input to UART from file 
- Virtual network interface with IP address
- Simulate random input from keys
- Print instruction cache statistics
I am currently working on getting the two first implemented.

**Comment by schoeberl** [comment]
Looks like we are in a bit of a mess. I tried to run the (nightly) test locally, including Verilator installed. I’ve seen some build error on the emulator, but the it run through. Maybe it ran with the emulator in the path of standard t-crest/local/bin instead of t-crest-test/local/bin. …

We should keep working on this to sort it out.

Martin

**Comment by schoeberl** [comment]
Just checked with the test folder in front of the path: patemu was not built with regtest.sh. When I ask “which patemu” the one in t-crest/local/bin shows up. with “which pasim” I get the one in t-crets-test/local bin.

When I try to build Patmos in the t-crest-test with ./misc.sh patmos I get:

../Patmos-harness.cpp: In member function ‘void Emulator::emu_uart()’:
../Patmos-harness.cpp:189:12: error: ‘class VPatmos’ has no member named ‘Patmos__DOT__UartCmp__DOT__uart_io_ocp_M_Cmd’
  189 |     if (c->Patmos__DOT__UartCmp__DOT__uart_io_ocp_M_Cmd == 0x1
      |            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../Patmos-harness.cpp:190:16: error: ‘class VPatmos’ has no member named ‘Patmos__DOT__UartCmp__DOT__uart_io_ocp_M_Addr’
  190 |         && (c->Patmos__DOT__UartCmp__DOT__uart_io_ocp_M_Addr & 0xff) == 0x04) {
      |                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
At global scope:

This is the issue.

Any ideas?

Cheers,
Martin

**Comment by schoeberl** [comment]
Maybe this issue is the main reason:

```
[32m ===== Processing 'patmos' ===== [0m
[32m ===== Building tools/c in patmos ..  ===== [0m
CMake Error at src/cmake_install.cmake:47 (file):
  file INSTALL cannot copy file
  "/home/martin/t-crest-test/patmos/tools/c/build/src/elf2bin" to
  "/usr/local/bin/elf2bin": Permission denied.
Call Stack (most recent call first):
  cmake_install.cmake:42 (include)


make: *** [Makefile:86: install] Error 1
```

Why do we want to copy any stuff into /usr/local/bin?

**Comment by schoeberl** [comment]
Update: the regression test did run all emulator tests on my local machine. But it does not on Helena. Mmh.

**Comment by schoeberl** [comment]
Probably it found an ```elf2bin``` in the t-crest installation on my machine when I run the regression test.

When I do on my local installation:
```
misc/build.sh patmos
```

```elf2bin``` is created and installed in ```t-crest/local/bin```. What is wrong with the regression test trying to install this tool in the wrong place?

**Comment by schoeberl** [comment]
Another possibility is missing/wrong version of Verilator on Helena.

**Comment by Emoun** [comment]
I think this issue is solved. Can someone who is subscribed to the nightly test check that the emulator is actually run and tested and close this issue.

**Comment by schoeberl** [comment]
Yes, it is fixed.
