### ISSUE TITLE
Add simulator tests to nightly regression test

### ISSUE THREAD

**Issue by schoeberl** [t-crest/patmos-misc#15]
Add the simulator test into: misc/build.sh (so it can be run with ```./misc/build.sh -t simulator```) and into regtest.sh

**Comment by Emoun** [comment]
Fixed this in 1f472ae7a9143eb801a7f0bf4d989801594ec38d. I will wait to see if it works as expected in tonight's test before closing this issue.

**Comment by Emoun** [comment]
Tonight's regression test worked as expected. Closing issue.
