### ISSUE TITLE
poseidon no built

### ISSUE THREAD

**Issue by schoeberl** [t-crest/patmos-misc#16]
When installing with -q (and toolchain2), poseidon is not built and therefore Argo does not work. Maybe need to be fixed before the summerschool.

**Comment by Emoun** [comment]
The summer school does not use `toolchain2`, so no issue. This is an easy fix, just need to add poseidon to the list of projects built under `toolchain2`. I can look into it when I'm back (next week).

**Comment by Emoun** [comment]
I've looked at the `build.sh`, and as far as I can see [poseidon is being built](https://github.com/t-crest/patmos-misc/blob/6dfc09b1d02ce0710778a7120d977dac6fbb845d/build.sh#L89). Could you please check again that it is not some other issue?

**Comment by schoeberl** [comment]
My fault, sorry. I missed a dependency on svn on my Mac.

```toolchain2``` can be useful for Mac users at the summer school. And you will have some ;-)
